# Using this convenient image which uses Node.js as a base
image: alekzonder/puppeteer:latest

# This folder is cached between builds for faster runs
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

before_script:
  - apt-get update -qy
  - npm ci
  - npm run build
  - npm run pdf

stages:
  - test

test-job:
  only:
    - main
  stage: test
  script:
    - npm run test
